parameters:
  - name: environment
    type: string
    default: "dev"

steps:
  - task: AzureCLI@2
    displayName: "Deploy infrastructure to the ${{ parameters.environment }} environment"
    inputs:
      azureSubscription: "goat-ticket-connection"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az deployment sub create \
          --location southeastasia \
          --template-file "$(Pipeline.Workspace)/s/InfraRepo/deploy/bicep/main.bicep" \
          --parameters "$(Pipeline.Workspace)/s/InfraRepo/deploy/variables/${{ parameters.environment }}.bicepparam"
    env:
      TICKET_QR_SIGNING_KEY_VALUE: $(ticketQrSigningKeyValue)
      KEY_VAULT_CERT_SECRET_URI: $(keyVaultCertSecretUri)
