# goat-ticket-infra/deploy/pipeline/templates/hybrid-deploy-infra.yml
parameters:
  - name: deployInfraFirst
    type: boolean
    default: false
  - name: appDeploySteps
    type: stepList
    default: []

stages:
  - stage: DeployInfra
    displayName: "Deploy infrastructure"
    condition: eq('${{ parameters.deployInfraFirst }}', 'true')
    jobs:
      - job: DeployInfraJob
        steps:
          - task: AzureCLI@2
            displayName: "Deploy infrastructure to the development environment"
            inputs:
              azureSubscription: "goat-ticket-connection"
              scriptType: "bash"
              scriptLocation: "scriptPath"
              scriptPath: "deploy/script/deploy-environment.sh"
              arguments: "dev deploy/variables/dev.bicepparam"
            env:
              TICKET_QR_SIGNING_KEY_VALUE: $(ticketQrSigningKeyValue)
              KEY_VAULT_CERT_SECRET_URI: $(keyVaultCertSecretUri)

  - stage: DeployCode
    displayName: "Deploy application code"
    dependsOn: DeployInfra
    condition: always()
    jobs:
      - job: BuildAndDeploy
        steps:
          - checkout: self
          - ${{ parameters.appDeploySteps }}
